name: darty_json_safe
description: A dart data parsing library modeled on swiftyjson
version: 1.0.0
homepage: https://github.com/josercc/darty_json
public_to: https://pub.dartlang.org

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
